<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BeatSaberPlaylistsLib" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SixLabors.Fonts" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeatSpiderSharp.Extensions\BeatSpiderSharp.Extensions.csproj" />
    <ProjectReference Include="..\BeatSpiderSharp.Legacy\BeatSpiderSharp.Legacy.csproj" />
    <ProjectReference Include="..\BeatSpiderSharp.Models\BeatSpiderSharp.Models.csproj" />
    <ProjectReference Include="..\BeatSpiderSharp.Shared\BeatSpiderSharp.Shared.csproj" />
  </ItemGroup>
</Project>
