<Project>
    <PropertyGroup>
        <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="BeatSaberPlaylistsLib" Version="1.6.6" />
        <PackageVersion Include="BeatSaverSharper" Version="3.4.5" />
        <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageVersion Include="Serilog" Version="4.2.0" />
        <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageVersion Include="Serilog.Sinks.File" Version="6.0.0" />
        <PackageVersion Include="SixLabors.Fonts" Version="2.1.2" />
        <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.6" />
        <PackageVersion Include="SixLabors.ImageSharp.Drawing" Version="2.1.5" />
        <PackageVersion Include="System.CommandLine" Version="2.0.0-beta5.25306.1" />
        <PackageVersion Include="System.IO.Compression" Version="4.3.0" />
    </ItemGroup>
</Project>
