<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeatSpiderSharp.Extensions\BeatSpiderSharp.Extensions.csproj" />
    <ProjectReference Include="..\BeatSpiderSharp.Models\BeatSpiderSharp.Models.csproj" />
  </ItemGroup>

</Project>
