<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="System.IO.Compression" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libs\BeatSpiderSharp.Shared\BeatSpiderSharp.Shared.csproj" />
  </ItemGroup>

</Project>
